// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG43ePPwA-rzWaePxaqa7K_3RTP4-uFbs',
    appId: '1:76913861450:web:47dbf679acd24e036f17b3',
    messagingSenderId: '76913861450',
    projectId: 'chatappjoflee',
    authDomain: 'chatappjoflee.firebaseapp.com',
    storageBucket: 'chatappjoflee.firebasestorage.app',
    measurementId: 'G-XP1P55PTP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwV6YSAR0OnH6dG_kLe5_J_zcfQjpVSpI',
    appId: '1:76913861450:android:9dee0dcb0cabd57e6f17b3',
    messagingSenderId: '76913861450',
    projectId: 'chatappjoflee',
    storageBucket: 'chatappjoflee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwjac8yF5jibvRq3MCVU5L0BLbd5eCSdk',
    appId: '1:76913861450:ios:ceb5ef30bbf74df56f17b3',
    messagingSenderId: '76913861450',
    projectId: 'chatappjoflee',
    storageBucket: 'chatappjoflee.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectsWeek6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwjac8yF5jibvRq3MCVU5L0BLbd5eCSdk',
    appId: '1:76913861450:ios:ceb5ef30bbf74df56f17b3',
    messagingSenderId: '76913861450',
    projectId: 'chatappjoflee',
    storageBucket: 'chatappjoflee.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectsWeek6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG43ePPwA-rzWaePxaqa7K_3RTP4-uFbs',
    appId: '1:76913861450:web:f4e322cfdb0e04786f17b3',
    messagingSenderId: '76913861450',
    projectId: 'chatappjoflee',
    authDomain: 'chatappjoflee.firebaseapp.com',
    storageBucket: 'chatappjoflee.firebasestorage.app',
    measurementId: 'G-MD0H0JG6MT',
  );
}
